"""ensure_users_table

Revision ID: f118559ed3a0
Revises: 3479409674ae
Create Date: 2025-08-18 14:23:06.397625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f118559ed3a0'
down_revision = '3479409674ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 